spring.application.name=ConfigServer
server.port=8888
spring.cloud.config.server.git.uri=https://github.com/akshay1kr1verma/centralconfig.git
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_ACCESS_TOKEN}
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=global, orderservice
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.timeout=10